### PR TITLE
Add JF_GIT_API_ENDPOINT Variable

### PR DESCRIPTION
**Pull request by 0c0c0f**
- [ ] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.

---

### CODE REVIEW

**Comment by eyalbe4** [comment]
@0c0c0f,
This PR is incomplete, correct?
Is the new environment variable this PR adds to the README is actually supposed by the Frogbot code? Can you elaborate more about that?

**Comment by eyalbe4** [comment]
Oh - I know see the code does support it @0c0c0f. Thanks!
Will you be able to sign the CLA as the bot comment suggests, so that we can merge your PR?

**Comment by 0c0c0f** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0c0c0f** [comment]
> Oh - I know see the code does support it @0c0c0f. Thanks! Will you be able to sign the CLA as the bot comment suggests, so that we can merge your PR?
agreed!  ref: https://github.com/jfrog/frogbot/pull/51#issuecomment-1107524021

**Pull request merged**
